apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: much-todo
data:
  MONGODB_DATABASE: "much_todo_db"
  # Necessary for the replica set initialization command
  REPLICA_SET_NAME: "rs0"