apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: much-todo
data:
  DB_NAME: "much_todo_db"
  MONGO_HOST: "mongodb-service"
  MONGO_URI: "mongodb://mongodb-service:27017"
  REDIS_HOST: "redis-service"
  LOG_LEVEL: "info"

