apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: much-todo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: backend-app:latest
          imagePullPolicy: Never
          workingDir: /app
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: backend-config
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
