apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: much-todo
type: Opaque
data:
  # Values are base64 encoded strings
  # 'root' = cm9vdA== | 'example' = ZXhhbXBsZQ==
  MONGO_USER: cm9vdA==
  MONGO_PASSWORD: ZXhhbXBsZQ==